#!/usr/bin/env bash
#
# Ballast quick start.
#
#   ./scripts/quickstart.sh
#
# Generates the secrets that can be generated, asks only for the ones that
# cannot, writes .env, and brings the stack up.
#
# The Google OAuth client id and secret are the only things this cannot create
# for you. Ballast has no password login by design (PRD §2: OIDC only, no
# password is ever stored), so there is no way to skip that step.
#
# Non-interactive use -- set them first and nothing is prompted:
#
#   AUTH_GOOGLE_ID=... AUTH_GOOGLE_SECRET=... SEED_ALLOWED_EMAILS=you@example.com \
#     ./scripts/quickstart.sh --yes

set -euo pipefail

cd "$(dirname "$0")/.."

ENV_FILE=".env"
COMPOSE_FILE="docker-compose.quickstart.yml"
ASSUME_YES=0
# An explicit if, not an `A || B && C` chain: under `set -e` the exit status of
# such a chain when nothing matches is shell-dependent, and it can abort here.
case "${1:-}" in
  --yes | -y) ASSUME_YES=1 ;;
  '') ;;
  *) printf 'unknown option: %s\n' "$1" >&2; exit 2 ;;
esac

say()  { printf '%s\n' "$*"; }
fail() { printf 'error: %s\n' "$*" >&2; exit 1; }

# ---------------------------------------------------------------- prerequisites

command -v docker >/dev/null 2>&1 || fail "docker is not installed."
docker compose version >/dev/null 2>&1 || fail "the docker compose plugin is not available."
docker info >/dev/null 2>&1 || fail "the docker daemon is not running."
command -v openssl >/dev/null 2>&1 || fail "openssl is needed to generate secrets."
[ -f "$COMPOSE_FILE" ] || fail "run this from the repository root ($COMPOSE_FILE not found)."

# ---------------------------------------------------------------- existing .env

if [ -f "$ENV_FILE" ]; then
  say "$ENV_FILE already exists — keeping it as it is."
  say "Delete it first if you want a fresh set of secrets."
else
  say "Setting up Ballast."
  say ""

  # Generated: no reason to make a human invent these.
  POSTGRES_PASSWORD="$(openssl rand -hex 24)"
  APP_DB_PASSWORD="$(openssl rand -hex 24)"
  AUTH_SECRET="$(openssl rand -base64 32)"

  # Asked for: these come from Google and cannot be generated here.
  if [ -z "${AUTH_GOOGLE_ID:-}" ]; then
    say "Ballast signs in with Google. Create an OAuth client (type: Web application) at"
    say "  https://console.cloud.google.com/apis/credentials"
    say "and set its authorised redirect URI to:"
    say "  ${AUTH_URL:-http://localhost:3000}/api/auth/callback/google"
    say ""
    say "Plain http is fine for localhost -- Google exempts it from the HTTPS rule."
    say "On the consent screen, set the user type to External and add every email"
    say "that will sign in under Test users, or Google will reject them."
    say ""
    read -r -p "Google client ID: " AUTH_GOOGLE_ID
  fi
  [ -n "${AUTH_GOOGLE_ID:-}" ] || fail "a Google client ID is required."

  if [ -z "${AUTH_GOOGLE_SECRET:-}" ]; then
    # -s: a pasted secret should not end up in the scrollback or shell history.
    read -r -s -p "Google client secret: " AUTH_GOOGLE_SECRET
    printf '\n'
  fi
  [ -n "${AUTH_GOOGLE_SECRET:-}" ] || fail "a Google client secret is required."

  if [ -z "${SEED_ALLOWED_EMAILS:-}" ]; then
    say ""
    say "Only these email addresses will be able to sign in."
    read -r -p "Allowed emails (comma separated): " SEED_ALLOWED_EMAILS
  fi
  [ -n "${SEED_ALLOWED_EMAILS:-}" ] || fail "at least one allowed email is required."

  umask 077 # the file holds secrets; do not create it world-readable
  cat > "$ENV_FILE" <<ENV
# Generated by scripts/quickstart.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Secrets. Not committed: .gitignore excludes .env

POSTGRES_USER=ballast
POSTGRES_DB=ballast
POSTGRES_PASSWORD=$POSTGRES_PASSWORD

# The restricted role the app connects as. It cannot UPDATE or DELETE events.
APP_DB_PASSWORD=$APP_DB_PASSWORD

AUTH_SECRET=$AUTH_SECRET
AUTH_GOOGLE_ID=$AUTH_GOOGLE_ID
AUTH_GOOGLE_SECRET=$AUTH_GOOGLE_SECRET
AUTH_URL=${AUTH_URL:-http://localhost:3000}

SEED_ALLOWED_EMAILS=$SEED_ALLOWED_EMAILS
SEED_HOUSEHOLD_NAME=${SEED_HOUSEHOLD_NAME:-Household}

HOUSEHOLD_TIMEZONE=${HOUSEHOLD_TIMEZONE:-America/Chicago}
APP_PORT=${APP_PORT:-3000}

# Optional: the app computes, n8n delivers. Leave blank and notifications are
# logged and dropped rather than failing anything.
N8N_WEBHOOK_URL=
N8N_WEBHOOK_TOKEN=
ENV

  say ""
  say "Wrote $ENV_FILE with generated database passwords and a fresh AUTH_SECRET."
fi

# ---------------------------------------------------------------- bring it up

if [ "$ASSUME_YES" -eq 0 ]; then
  say ""
  read -r -p "Build and start Ballast now? [Y/n] " reply
  case "$reply" in [nN]*) say "Stopped. Start it later with:"; say "  docker compose -f $COMPOSE_FILE up -d --build"; exit 0 ;; esac
fi

say ""
say "Building and starting…"
# The revision being built, so the app can tell whether the published image
# has moved on. Absent git (a downloaded tarball), the footer says so instead.
GIT_SHA="$(git rev-parse HEAD 2>/dev/null || true)"
export GIT_SHA
docker compose -f "$COMPOSE_FILE" up -d --build

# shellcheck disable=SC1090
APP_PORT="$(grep -E '^APP_PORT=' "$ENV_FILE" | cut -d= -f2)"
AUTH_URL="$(grep -E '^AUTH_URL=' "$ENV_FILE" | cut -d= -f2-)"

say ""
say "Ballast is starting at ${AUTH_URL:-http://localhost:${APP_PORT:-3000}}"
say ""
say "The first start migrates the database, sets up the restricted role and"
say "seeds the household. Watch it happen with:"
say "  docker compose -f $COMPOSE_FILE logs -f app"
say ""
say "If sign-in fails, the redirect URI on your Google OAuth client must be"
say "exactly: ${AUTH_URL:-http://localhost:${APP_PORT:-3000}}/api/auth/callback/google"
